// protoc-gen-es-lite is es-lite's code generator. For every message
// annotated with (es.v1.sum_type), it emits — into that message's own Go
// package — a sealed interface over the oneof's variants, a marker method
// on each variant, and an es.Codec implementation. This is the file the
// hand-written counter_es.go previously stood in for.
//
// It is a standard protoc/buf plugin: it reads a CodeGeneratorRequest on
// stdin and writes a CodeGeneratorResponse on stdout. Wire it via
// buf.gen.yaml (`local: protoc-gen-es-lite`).
package main

import (
	"fmt"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"

	esv1 "github.com/laenenai/es-lite/gen/es/v1"
)

// Import paths referenced by generated code.
const (
	protoPkgPath = protogen.GoImportPath("google.golang.org/protobuf/proto")
	esPkgPath    = protogen.GoImportPath("github.com/laenenai/es-lite/es")
	fmtPkgPath   = protogen.GoImportPath("fmt")
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		// The generated code uses proto3; advertise support so buf does
		// not warn on optional fields.
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

// sumType is one annotated container: its generated interface name, the
// variant messages of its oneof, and any non-default schema versions
// (keyed by full proto type name) declared via (es.v1.schema_version).
type sumType struct {
	iface      string
	variants   []*protogen.Message
	nonDefault map[string]uint32
}

func generateFile(gen *protogen.Plugin, f *protogen.File) error {
	var sums []sumType
	for _, m := range f.Messages {
		name, err := sumTypeName(m)
		if err != nil {
			return err
		}
		if name == "" {
			continue
		}
		if len(m.Oneofs) != 1 {
			return fmt.Errorf("%s: (es.v1.sum_type) requires exactly one oneof, found %d", m.Desc.FullName(), len(m.Oneofs))
		}
		st := sumType{iface: name}
		for _, field := range m.Oneofs[0].Fields {
			if field.Message == nil {
				return fmt.Errorf("%s: sum-type variant %q must be a message", m.Desc.FullName(), field.Desc.Name())
			}
			st.variants = append(st.variants, field.Message)
			if v := schemaVersionOf(field.Message); v != 1 {
				if st.nonDefault == nil {
					st.nonDefault = map[string]uint32{}
				}
				st.nonDefault[string(field.Message.Desc.FullName())] = v
			}
		}
		sums = append(sums, st)
	}
	if len(sums) == 0 {
		return nil // nothing to generate for this file
	}

	g := gen.NewGeneratedFile(f.GeneratedFilenamePrefix+"_es.pb.go", f.GoImportPath)
	g.P("// Code generated by protoc-gen-es-lite. DO NOT EDIT.")
	g.P("//")
	g.P("// Source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	for _, st := range sums {
		writeSumType(g, st)
	}
	return nil
}

func writeSumType(g *protogen.GeneratedFile, st sumType) {
	proto := g.QualifiedGoIdent(protoPkgPath.Ident("Message"))
	marshal := g.QualifiedGoIdent(protoPkgPath.Ident("Marshal"))
	unmarshal := g.QualifiedGoIdent(protoPkgPath.Ident("Unmarshal"))
	encodedEvent := g.QualifiedGoIdent(esPkgPath.Ident("EncodedEvent"))
	codec := g.QualifiedGoIdent(esPkgPath.Ident("Codec"))
	unknownErr := g.QualifiedGoIdent(esPkgPath.Ident("ErrUnknownEventType"))
	errorf := g.QualifiedGoIdent(fmtPkgPath.Ident("Errorf"))

	iface := st.iface
	marker := "is" + iface

	// Sealed interface + marker methods.
	g.P("// ", iface, " is the sealed sum type over the annotated oneof's variants.")
	g.P("type ", iface, " interface{ ", marker, "() }")
	g.P()
	for _, v := range st.variants {
		g.P("func (*", g.QualifiedGoIdent(v.GoIdent), ") ", marker, "() {}")
	}
	g.P()

	// Codec.
	codecType := iface + "Codec"
	g.P("// ", codecType, " marshals each ", iface, " variant as canonical proto")
	g.P("// bytes tagged with its full proto type name.")
	g.P("type ", codecType, " struct{}")
	g.P()
	g.P("var _ ", codec, "[", iface, "] = ", codecType, "{}")
	g.P()

	// Encode.
	schemaFn := lowerFirst(iface) + "SchemaVersion"
	g.P("func (", codecType, ") Encode(v ", iface, ") (", encodedEvent, ", error) {")
	g.P("	m, ok := v.(", proto, ")")
	g.P("	if !ok {")
	g.P("		return ", encodedEvent, "{}, ", errorf, "(\"", iface, "Codec: %T is not a proto.Message\", v)")
	g.P("	}")
	g.P("	b, err := ", marshal, "(m)")
	g.P("	if err != nil {")
	g.P("		return ", encodedEvent, "{}, err")
	g.P("	}")
	g.P("	typeURL := string(m.ProtoReflect().Descriptor().FullName())")
	if len(st.nonDefault) == 0 {
		g.P("	return ", encodedEvent, "{TypeURL: typeURL, SchemaVersion: 1, Payload: b}, nil")
	} else {
		g.P("	return ", encodedEvent, "{TypeURL: typeURL, SchemaVersion: ", schemaFn, "(typeURL), Payload: b}, nil")
	}
	g.P("}")
	g.P()

	// Per-variant schema version lookup (only when some variant overrides
	// the default of 1). Cases are emitted in variant declaration order for
	// deterministic output.
	if len(st.nonDefault) > 0 {
		g.P("func ", schemaFn, "(typeURL string) uint32 {")
		g.P("	switch typeURL {")
		for _, v := range st.variants {
			name := string(v.Desc.FullName())
			if ver, ok := st.nonDefault[name]; ok {
				g.P("	case ", fmt.Sprintf("%q", name), ":")
				g.P("		return ", ver)
			}
		}
		g.P("	default:")
		g.P("		return 1")
		g.P("	}")
		g.P("}")
		g.P()
	}

	// Decode.
	g.P("func (", codecType, ") Decode(enc ", encodedEvent, ") (", iface, ", error) {")
	g.P("	var msg ", proto)
	g.P("	switch enc.TypeURL {")
	for _, v := range st.variants {
		g.P("	case ", fmt.Sprintf("%q", string(v.Desc.FullName())), ":")
		g.P("		msg = &", g.QualifiedGoIdent(v.GoIdent), "{}")
	}
	g.P("	default:")
	g.P("		return nil, ", errorf, "(\"%w: %q\", ", unknownErr, ", enc.TypeURL)")
	g.P("	}")
	g.P("	if err := ", unmarshal, "(enc.Payload, msg); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	return msg.(", iface, "), nil")
	g.P("}")
	g.P()
}

// sumTypeName returns the (es.v1.sum_type) value on a message, or "" if
// unset.
func sumTypeName(m *protogen.Message) (string, error) {
	opts := m.Desc.Options()
	if opts == nil {
		return "", nil
	}
	if !proto.HasExtension(opts, esv1.E_SumType) {
		return "", nil
	}
	name, ok := proto.GetExtension(opts, esv1.E_SumType).(string)
	if !ok {
		return "", fmt.Errorf("%s: (es.v1.sum_type) is not a string", m.Desc.FullName())
	}
	return name, nil
}

// schemaVersionOf returns the (es.v1.schema_version) on a variant message,
// defaulting to 1 when unset or zero.
func schemaVersionOf(m *protogen.Message) uint32 {
	opts := m.Desc.Options()
	if opts == nil || !proto.HasExtension(opts, esv1.E_SchemaVersion) {
		return 1
	}
	v, ok := proto.GetExtension(opts, esv1.E_SchemaVersion).(uint32)
	if !ok || v == 0 {
		return 1
	}
	return v
}

// lowerFirst lowercases the first rune, turning an exported interface name
// into an unexported helper name (e.g. "Event" -> "eventSchemaVersion").
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
